### ISSUE TITLE
Quick fix for empty response

### ISSUE THREAD

**Issue by AyhamAl-Ali** [emermacko/download-snap-memories#2]
The code works perfectly, I like it however, I have had a small issue with some memories saying:

`[ERROR]  Invalid URL '': No schema supplied. Perhaps you meant http://?`

not sure why this happened, it is probably a problem from snapchat memory url, I tried to download it myself and it took too long and didn't download at the end.

I made a quick fixed by adding this code

```
                if response == '':
                    print("Couldn't download memory of date {}".format(date))
                    continue
```
before `file = requests.get(response)`

and it worked perfectly.

**Comment by emermacko** [comment]
Hi, I've also encountered this error and I linked it to the expiration of Snapchat URLs.

As I manually try to download any memory from the `.html` file it says `Oops! Something went wrong. Status 403`.
And whenever I request new data it starts working again.

But if you say you managed to start the download manually it may also be connected to some other errors.

So thanks for bringing this up and providing the solution.
I will add the error message and the continue statement.
