### ISSUE TITLE
Thank you so much 🙏

### ISSUE THREAD

**Issue by every-name-is-taken** [emermacko/download-snap-memories#23]
I know this isn't an issue but you save me about a week of work! 🤗

I did encounter a program when trying to run the program (I'm on android) trying to install the requirements did not work so I had to try run 'python3 run.py' and then use 'pip install <<whatever the error stated>>' a few times but other than that I genuinely can't thank you enough 🙏

**Comment by macie-k** [comment]
Good to know:) Glad I could help!
