### ISSUE TITLE
noob

### ISSUE THREAD

**Issue by flowergirlrose** [emermacko/download-snap-memories#3]
when I download your program, it shows up as a .py file? I followed your video but that part opens up completely different for me than the thing you open up

**Comment by flowergirlrose** [comment]
when I click to open the .py file this shows up:

import json
import requests
import os
import datetime

from tqdm import tqdm

try:
    from win32_setctime import setctime
except: # for linux
    pass

def downloadMemories(path):
    clear()

    with open(path, 'r') as f:
        content = json.load(f)
        media = content['Saved Media']
        print(f'[OK] Found {len(media)} files')

        if not os.path.exists('memories'):
            try:
                os.mkdir('memories')
                print('[OK] Directory created\n')
            except Exception as e:
                input(f'[ERROR] Could not create directory: {e}')
                exit()

        for data in tqdm(media, desc="[OK] Downloading: ", unit="file", ncols=70, bar_format="{desc}{n_fmt}/{total_fmt} {bar}{percentage:3.0f}%"):

            date = data['Date']
            url = data['Download Link']
            filetype = data['Media Type']

            day = date.split(" ")[0]
            time = date.split(" ")[1].replace(':', '-')
            filename = f'memories/{day}_{time}.mp4' if filetype == 'VIDEO' else f'memories/{day}_{time}.jpg'

            if not os.path.exists(filename):
                req = requests.post(url, allow_redirects=True)
                response = req.text

                if response == '':
                    print(f'\n\n[ERROR] Could not download memory: {filename[9:]}')
                    print('[!] If this error persists request new data\n')
                    continue

                file = requests.get(response)
                timestamp = datetime.datetime.timestamp(datetime.datetime.strptime(day + '-' + time, "%Y-%m-%d-%H-%M-%S"))

                with open(filename, 'wb') as f:
                    f.write(file.content)
                    
                os.utime(filename, (timestamp, timestamp))
                if os.name=='nt':   ## only for windows overrite creation time
                    setctime(filename, timestamp)
        print('\n\n---------------- ')
        input('[OK] Finished ')
        exit()

clear = lambda: os.system('cls' if os.name=='nt' else 'clear')

try:
    path = 'json/memories_history.json' if os.path.exists('json') else 'memories_history.json'
    downloadMemories(path)
except Exception as e:
    input(f'[ERROR] {e}')

**Comment by emermacko** [comment]
Hi, it seems like you downloaded the source file.
Go [here](https://github.com/emermacko/download-snap-memories/releases) and click on `download_memories.exe` in `Assets`
![image](https://user-images.githubusercontent.com/25122875/97626168-bd7d0300-1a29-11eb-89c9-72429b7a261d.png)

Check, if the browser correctly downloaded the file, as it may block it.
You should now have a file with the `.exe` extension, simply double click on it to run the script.
