### ISSUE TITLE
MacOS with Python 2.7.16

### ISSUE THREAD

**Issue by steliosaa** [emermacko/download-snap-memories#4]
Get a syntax error at line 25

File "download_memories.py", line 25
    success(f'Found {len(media)} files')
                                      ^
SyntaxError: invalid syntax

**Comment by emermacko** [comment]
Hi, the script requires `Python 3.8` or higher

**Comment by steliosaa** [comment]
Finally made it work. Maybe this can be added to the readme for MacOS (BigSur)

First download homebrew for mac:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Then downloading python3 from homebrew for mac 
`brew install pyenv 
pyenv install --list
(CHOOSE THE NEWEST ONE - AS OF TODAY IT WAS 3.9.0)
pyenv install 3.9.0`

I added the 3 dependencies which were missing (from readme) and also a 4th one (tqdm) not mentioned in the readme, using pip3.

`pip3 install requests 
pip3 install win32-setctime
pip3 install colorama
pip3 install tqdm`

then run the script with "python3" instead of "python" after going to the directory where the python script and the javascript (copy it same way as in the YouTube video) are located.
`cd "DIRECTORY OF THE SCRIPT"
python3 download_memoris.py`

**Comment by emermacko** [comment]
Thank you for providing all that information.
I will add the required python version as well as the `tqdm` dependency to README.

I will also create a `docs` folder, to keep the README clean, with more precise installation instructions for Linux and, based on your answer, macOS.
