### ISSUE TITLE
Error Downloading past File 24

### ISSUE THREAD

**Issue by shayjordan134** [emermacko/download-snap-memories#7]
UPDATE: *RESOLVED* I just had to add a randomly generated string to the end of the filename and it resolved the issues.

Hi there,
I've tried downloading my snapchat files with your program a few times now and have requested my snapchat data a couple of different times, but with each time I do it the process seems to hit an error when it reaches file 24. Below is the error message I'm getting:

[ERROR] Exception occured: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>

I'm on macOS Big Sur and my internet connection is stable whilst I'm running it, and I have tried removing the 23rd, 24th and 25th files from the JSON file but it still seems to hit the same barrier, independent of what the 24th file actually is. There doesn't seem to be an issue with downloading the files manually via the links on the HTML file provided by snapchat. Do you know what the issue is here? Thanks.

EDIT: On further inspection, it seems to happen when there are two files which share the same time-stamp (i.e. when there is a video that lasts longer than 10 seconds and is hence split into 2 or more files.)

ANOTHER EDIT: Actually, it doesn't happen ALL the time for videos split into multiple files, but it does seem to be the case for ones which have the same timestamp across all files (I'm not sure why some do and some don't share the same timestamp).

**Comment by emermacko** [comment]
Hi, thanks for all the details about the problem and how you solved it.
There are some things that need to be clarified though.

The problem with duplicated timestamps should no longer occur after the `1.10` update and it also seems to be unrelated to the SSL Certificate error at all.

According to [this](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/45018725#comment93046025_45018725) answer, the error might be related to your OS.
So try running this command:
```bash
$ pip install certifi
$ /Applications/Python\ 3.6/Install\ Certificates.command
```
or
``` bash
$ sudo /Applications/Python\ 3.x/Install\ Certificates.command
```
In both cases replace the `x` with your version

**Comment by shayjordan134** [comment]
Ah, yes - that seems to have fixed it too. Thank you. Do you have any idea why my fix also worked? I did recognise that it didn't seem to directly relate to the error message or SSL certificates, so I was confused the it fixed the issue!

**Comment by emermacko** [comment]
Glad to hear it worked, I will update the installation instructions for macOS. 

Answering your question; You mentioned that you were changing the filename, now if the script detects that the file already exists (when you don't rename it) it's checking whether it is a duplicated memory, by reading the new file's size from the headers.

So it seems that the request for headers might have been the issue.

**Comment by shayjordan134** [comment]
Ahh, that makes sense. Thanks for the clarification on that! (And thank you for creating this program too - it’s served really useful!)
